### PR TITLE
Adds CAS Common API tutorial, fixes #5.

### LINKED ISSUE #5: Add CAS Common Chem tutorial?
Here is a python tutorial for CAS Common Chem to consider adding. It's licensed as MIT, so we could reproduce a copy in the WFChemCookbook. thoughts? 

https://ualibweb.github.io/UALIB_ScholarlyAPI_Cookbook/content/scripts/python/python_casc.html

### PR DESCRIPTION
**Pull request by vfscalfani**
Needs a reviewer maybe before merging with main. Thanks @stuchalk !

### CODE REVIEW

**Comment by stuchalk** [comment]
Vin, thanks for this I will take a look.

**Comment by stuchalk** [comment]
Generally, there needs to be text to explain what the code is doing in each block, where there is none currently.  This does not need to be much. Something allowing the user to understand what each code statement translates to would be really helpful.

Specifically,
- A little more in the introduction indicating that the different sections get more and more complicated because of the amount of data retrieved...
- In block the fourth block of section 2 'vew' should be 'view' (comment)
- In Section 3 'Handle' should be 'Handling' (in two subtitles)
- Could you add a couple of suggestions for other things to try? Nothing big, but asking to apply what they have learned...

**Comment by stuchalk** [comment]
Additional checking of the Python code reveals that 'import json' present in three places is not used and thus can be deleted. In addition, the 'import numpy' in the last section is also not used...and so should be removed.

**Comment by stuchalk** [comment]
Vin, if you can update the PR by removing the updated _toc.yml file, then I can work on it.  We are not expected contributors to edit the TOC file ;)

**Review by stuchalk — CHANGES_REQUESTED** [review]
Vin, if you can remove the update of the toc.yml file (I will take care of it when I add it to the Cookbook) then I will approve this contribution.

**Comment by vfscalfani** [comment]
Thanks, TOC change should be removed now.

**Review by stuchalk — APPROVED** [review]
This looks like a great addition to the Cookbook!

**Pull request merged**
